### PR TITLE
LSP MBC presets completed

### PR DESCRIPTION
**Pull request by Digitalone1**
Linked all the presets.

I have issues on loading, wrote about it in #1031

The plugin works. It only remains to link frequency_end and reduction plugin ports to their labels inside the UI. I think "reduction" is the gain. "Curve level" is the band level instead? There's also "envelope meter" which I don't have any clue what it is, maybe the band sidechain level? I don't even know if is useful to show it the UI.

Can you suggest me how to link these ports to show them in the UI?

About the tests, nothing wrong except that I keep getting a critical log line during the application shutdown

```
(easyeffects:6103): easyeffects-DEBUG: 11:37:45.364: application_ui: destroyed

(easyeffects:6103): GLib-GIO-CRITICAL **: 11:37:45.389: g_application_release: assertion 'application->priv->use_count > 0' failed
(easyeffects:6103): easyeffects-DEBUG: 11:37:45.390: application:  destroyed
(easyeffects:6103): easyeffects-DEBUG: 11:37:45.390: presets_manager: destroyed
(easyeffects:6103): easyeffects-DEBUG: 11:37:45.391: sie: destroyed
(easyeffects:6103): easyeffects-DEBUG: 11:37:45.391: effects_base: destroyed

```

### CODE REVIEW

**Comment by wwmm** [comment]
>I think "reduction" is the gain.

It seems so. The plugin ttl file has
```
a lv2:OutputPort, lv2:ControlPort ;
lv2:index 65 ;
lv2:symbol "rlm_0" ;
lv2:name "Reduction level meter 0" ;
units:unit [
                        a units:Unit ;
                        rdfs:label "gain" ;
                        units:symbol "G" ;
                        units:render "%.8f G" ;
 ] ;
lv2:portProperty pp:logarithmic, pp:hasStrictBounds ;
lv2:minimum 0.000000 ;
lv2:maximum 3981.072998 ;
lv2:default 0.000000 ;
```
The label is set to `gain`.

>"Curve level" is the band level instead?

I think this is that dot that moves over the compressor curve graph. For now let's just call it `Curve Level`.

>There's also "envelope meter" which I don't have any clue what it is, maybe the band sidechain level?

>About the tests, nothing wrong except that I keep getting a critical log line during the application shutdown

I do not have this error. I think you may be seeing them because of the gsettings error.

I am not sure about what this is measuring. But based on what is written in this link https://en.wikipedia.org/wiki/Envelope_detector it seems to be the average or peak level of the envelop curve. It is probably better to just call it `Envelope Level`.

>Can you suggest me how to link these ports to show them in the UI?

I think I can do that today. I will take a look at it and update the lsp branch. I will also run clang-format on a few files.

**Comment by Digitalone1** [comment]
Envelope and curve level meter bars should be added to the UI. I put the gain level bar on top of the sidechain expander. But with the addition of the other two bars, I don't know if this is a good idea or it's better to move all of them at the bottom.

After the implementation of the lsp mbc, are you OK on replacing the calf limiter with the lsp one?

**Comment by wwmm** [comment]
>But with the addition of the other two bars, I don't know if this is a good idea or it's better to move all of them at the bottom.

I also think that this may become necessary. Let me handle the connection of these signals first. Now I remember why I did not do that before... But I think I can still do that today.

>After the implementation of the lsp mbc, are you OK on replacing the calf limiter with the lsp one?

I almost did that a long time ago. But at the time it did not seem to have as many advantages as the move to the lsp compressor had. To me it is fine moving to the lsp limiter.

**Comment by wwmm** [comment]
I was able to find a solution for the signals connections that I think it is acceptable. I connected only the frequency range signal and the band gain.I am not sure yet about how we can deal with the insane range that the band gain has. It goes from zero to `3981.072998`. After setting the gtk scale to this max value we can not even see most of the values in the level bar
Screenshot from 2021-08-01 12-41-47
When the compressor is in the downward mode the gain stays between 0 and 1. The other modes can go from 1 to this insane high level. I think that we will have to check in which mode the compressor is whenever a new signal comes and update the max level of the gtk scale accordingly. What may not be that good for performance. But I am not seeing another way...

I have also included the multiband in the latency reporting shown in our window bottom panel. When setting a lookahead value above zero this plugin introduces latency.

**Comment by wwmm** [comment]
>It goes from zero to 3981.072998

Linear scale.

**Comment by wwmm** [comment]
The lsp branch already has these changes in case you want to update yours.

**Comment by wwmm** [comment]
I have added the envelope and the curve level meters
Screenshot from 2021-08-01 13-05-29
Same problem with the scale range. And the plugin interface height is a lot bigger.

The lsp branch has already been updated with these changes

**Comment by wwmm** [comment]
I think there is not need to write `Band Gain` or `Band Envelope`. Just `'Gain` and `Envelope` is enough. Same thing for the curve level meter.

**Comment by wwmm** [comment]
Maybe one solution to the height problem is putting the compressor widgets also inside an expander.

**Comment by wwmm** [comment]
While switching presets I also saw the error 
```
Settings schema 'com.github.wwmm.easyeffects.multibandcompressor' does not contain a key named 'compression-mode'
```
Something is not right in the class `MultibandCompressorPreset`

**Comment by wwmm** [comment]
Problem fixed. Some keys were missing a `+ nstr` in the code.

**Comment by wwmm** [comment]
I think that this branch is good enough to be merged to the master. There is the issue with the level meters scale and the window height. But it is something that can be fixed.

**Comment by wwmm** [comment]
Merge done. I will delete the lsp_mbc branch

**Comment by Digitalone1** [comment]
> I am not sure yet about how we can deal with the insane range that the band gain has. It goes from zero to `3981.072998`. After setting the gtk scale to this max value we can not even see most of the values in the level bar

My suggestion is to just show only the 3 labels on one row and get rid of the level bars.

**Comment by wwmm** [comment]
>My suggestion is to just show only the 3 labels on one row and get rid of the level bars.

This crossed my mind. I am not convinced these level bars are worth the trouble.

**Comment by Digitalone1** [comment]
> This crossed my mind. I am not convinced these level bars are worth the trouble.

As I'm seeing, this levels are also available for the singleband compressor, but we don't show them. We are not forced to show them, but at least for the multiband compressor putting them on one line without levelbars is the best solution.

**Pull request merged**
