### PR TITLE
Add development build profile

### PR DESCRIPTION
**Pull request by vchernin**
This adds a meson option `-Ddevel=true|false`. @wwmm please test building locally to make sure this makes sense. I tested in fedora using just meson and ninja, and with the flatpak build.

This adds a optional new app id `com.github.wwmm.easyeffects.Devel`. This is especially useful for Flatpak users as apps with same ID always share their user data. Now if you build the flatpak using the manifest here you will get a development build which doesn't share data with the stable build. So e.g. you can leave the stable build and its configs untouched while you experiment and maybe break things in the devel build.

This also adds a devel css class which adds a construction tape looking header bar, to make it obvious in screenshots if this is a development build. There is a corresponding devel icon as well.

Notably gsettings/gschemas internally are left always using `com.github.wwmm.easyeffects` as it is useful to not impact the settings in case someone wants to copy/edit them (but this does not impact the flatpak builds being isolated).

The main possibility for error is if the wrong id is used say for gsettings, so I specifically named them `APP_ID_BUILD` (everything but gsettings) and `tags::app::id_canonical` (gsettings). 

Another drawback is you will never see "there is nothing to do" from ninja since meson must always check the commit before it starts the build, it has no reliable way to watch git itself. But it shouldn't have a serious impact.

Also this includes the commit in the about page for https://github.com/wwmm/easyeffects/issues/1681, but that is all for now.

### CODE REVIEW

**Comment by wwmm** [comment]
>The main possibility for error is if the wrong id is used say for gsettings, so I specifically named them APP_ID_BUILD (everything but gsettings) and tags::app::id_canonical (gsettings).

Tomorrow I will try to do some tests. But looking at the code things seems mostly fine. The renaming from `id` to `id_canonical` that feels a little weird. It isn't really clarifying things. As most of the code using this variable is gsettings code and both releases will use the same gsettings path I think it is better to keep the name as `id` and use `conf.set_quoted` to define a bool variable named like `IS_DEVEL_BUILD` or similar to select the correct string where it is necessary or in situations like `if (tags::app::id_canonical != app_id_build)`.

**Comment by vchernin** [comment]
> The renaming from `id` to `id_canonical` that feels a little weird. It isn't really clarifying things. As most of the code using this variable is gsettings code and both releases will use the same gsettings path I think it is better to keep the name as `id` and use `conf.set_quoted` to define a bool variable named like `IS_DEVEL_BUILD` or similar to select the correct string where it is necessary or in situations like `if (tags::app::id_canonical != app_id_build)`.

I can revert the `id` -> `id_canonical` commit easily enough. 

I originally had a conf.set_quoted for a devel bool like you suggest but I removed it since we only need to check it in one spot, but it could be readded. I wasn't sure what the sane way to read the `IS_DEVEL_BUILD` variable would be since it would be "true" or "false" and reading from a file.

**Comment by wwmm** [comment]
>I wasn't sure what the sane way to read the IS_DEVEL_BUILD variable would be since it would be a string "true" or "false", reading from config.h.

DEfiningas a string would not be good indeed. I think Meson has another function similar to `set_quoted` that is able to define an integer. Maybe it is `conf.set`. I would have to check in its docs but I am almost sure I used it before.

**Comment by wwmm** [comment]
There is a way to define a boolean https://mesonbuild.com/Configuration.html
```
conf_data.set10(token, boolean_value)
# The line above is equivalent to this:
if boolean_value
  conf_data.set(token, 1)
else
  conf_data.set(token, 0)
endif
```

**Comment by wwmm** [comment]
Not related to the PR but almost 60 minutes have passed and the aarch64 CI is still compiling the code :smile:

**Comment by vchernin** [comment]
> There is a way to to do it without strings https://mesonbuild.com/Configuration.html

Thanks, this worked much better. 

> Not related to the PR but almost 60 minutes have passed and the aarch64 CI is still compiling the code

It is technically related to the PR since I changed some build configs to speed up some dependency builds, but that then requires a rebuild. I will disable the aarch64 builds anyhow as it is obvious it will just sometimes be very slow since it is not terribly uncommon to need to edit the Flatpak dependencies. At least with Flatpak I have never seen any differences build wise with aarch64.

**Pull request merged**
