### PR TITLE
realtime_kit: Port to GDBus

### PR DESCRIPTION
**Pull request by jtojnar**
There is no need to use libdbus, GLib contains its own implementation.

Builds but I did not test this yet.

Also this is mostly 1:1 port to low-level GDBus API, in the future, it could be simplified using higher-level APIs.

### Relevant docs
- https://dbus.freedesktop.org/doc/dbus-specification.html#basic-types
- https://dbus.freedesktop.org/doc/api/html/group__DBusConnection.html
- https://developer.gnome.org/gio/stable/GDBusConnection.html
- https://developer.gnome.org/glibmm/2.53/classGio_1_1DBus_1_1Connection.html

### CODE REVIEW

**Comment by jtojnar** [comment]
Hmm, I am getting

```python
(pulseeffects:4157): pulseeffects-WARNING **: 04:02:34.380: sie: rtkit: The connection is closed

(pulseeffects:4157): pulseeffects-WARNING **: 04:02:34.380: sie: rtkit: The connection is closed
fish: “env G_MESSAGES_DEBUG=pulseeffec…” terminated by signal SIGSEGV (Address boundary error)
```

**Comment by wwmm** [comment]
I am testing it now and I get the same here. The crash happens in the method `get_int_property`. For some reason at the time `r = bus->send_message_with_reply_sync(m, -1);` is called the connection is closed

**Comment by jtojnar** [comment]
I guess I need to move reading the reply to the try block but I am still not sure how it would have worked before if similar issue was encountered. And also why the connection is getting closed.

**Comment by wwmm** [comment]
I tried to create the connection with `bus = Gio::DBus::Connection::get_sync(Gio::DBus::BUS_TYPE_SYSTEM);` and it goes ahead. But crashes in other sections with these messages:
```
(pulseeffects:8010): GLib-GIO-WARNING **: 11:44:25.199: g_dbus_message_set_serial: Attempted to modify a locked message

(pulseeffects:8010): GLib-GIO-WARNING **: 11:44:25.199: g_dbus_message_set_serial: Attempted to modify a locked message

(pulseeffects:8010): pulseeffects-WARNING **: 11:44:25.199: sie: rtkit:  : Expected value of type i or x but received (v)

(pulseeffects:8010): pulseeffects-WARNING **: 11:44:25.200: sie: rtkit:  : Expected value of type i or x but received (v)

(pulseeffects:8010): GLib-GIO-WARNING **: 11:44:25.203: g_dbus_message_set_serial: Attempted to modify a locked message
(pulseeffects:8010): pulseeffects-DEBUG: 11:44:25.203: sie: rtkit: changed GstQueue:eq_queue_L thread real-time priority value to 4
```
But it at least was able to set the priority in one of the threads...

**Comment by jtojnar** [comment]
> Expected value of type i or x but received (v)

This I understand. I saw in [Bustle](https://gitlab.freedesktop.org/bustle/bustle) that rtkit sends `@v <@x 200000>` instead of just `@x 200000` one would expect. That explains why the iterator code was so complicated.

**Comment by jtojnar** [comment]
I cleaned it up a bit with [`call_sync`](https://developer.gnome.org/glibmm/2.53/classGio_1_1DBus_1_1Connection.html#a0453f36932222ac59684548c5e7e7a87) method, no longer creating the `Message` manually. But am still no wiser why the connection gets closed.

If I dump the closed status at the top of the `get_int_property` method, it shows `0` but the dbus call still fails few lines down.

```
util::warning(log_tag + "get_int_property: bus.closed=" + std::to_string(bus->is_closed()));
```

**Comment by jtojnar** [comment]
Another simplification with the use of high-level `DBus::Proxy` API. Now it crashes with some broken assertions.

**Comment by jtojnar** [comment]
Finally got it to work – I was forgetting about the fact that the reply is boxed in a tuple.

But I do not really like the need to explicitly use `org.freedesktop.DBus.Properties` proxy. I would much prefer to just use [`g_dbus_proxy_get_cached_property`](https://developer.gnome.org/gio/stable/GDBusProxy.html#g-dbus-proxy-get-cached-property) but it just returns `NULL`, contrary to what the [constructor](https://developer.gnome.org/glibmm/2.53/classGio_1_1DBus_1_1Proxy.html#af3d7e5ea04b9f27862067372f42f2887) would lead me to believe.

**Pull request merged**
