### PR TITLE
Try to connect pw filters once when needed

### PR DESCRIPTION
**Pull request by Digitalone1**
Related to #1062

### CODE REVIEW

**Comment by wwmm** [comment]
Handling the call to `connect_to_pw` inside `EffectsBaseUi` is not a good idea. That class is instantiated only when the window is opened. If we start in service mode `connect_to_pw` will never be called.

**Comment by Digitalone1** [comment]
> Handling the call to `connect_to_pw` inside `EffectsBaseUi` is not a good idea. That class is instantiated only when the window is opened. If we start in service mode `connect_to_pw` will never be called.

I tried to do it in process method, but on_process function is not executed when the filter is disconnected, so it will never be connected. 

Where do you suggest to do it?

**Comment by wwmm** [comment]
>I tried to do it in process method, but on_process function is not executed when the filter is disconnected, so it will never be connected.

Yes. The on_process methos is called only when the plugin is linked and processing audio buffers. So even if it were connected it would not be enough.

There are two two things to keep in mind when starting in service mode. We have to read the plugins order that is already saved and link the filters accordingly. So when initializing we have to read the plugins array and connect the ones we will need before trying to link them.

The second thing is that the plugins array may change. So just like it is already done somewhere else  a signal connection like `settings->signal_changed("plugins").connect()` will have to be made. Inside the connect callback we will have to check again if the filters we need are connected and if not we have to connect them before trying to do the link.

**Comment by wwmm** [comment]
Or maybe to check for the connection before trying to do the link is enough

 https://github.com/wwmm/easyeffects/blob/13b0ab00657f2e369920a4bdbe6b71ce17aa74ba/src/stream_output_effects.cpp#L156

https://github.com/wwmm/easyeffects/blob/13b0ab00657f2e369920a4bdbe6b71ce17aa74ba/src/stream_input_effects.cpp#L160

**Comment by Digitalone1** [comment]
I'll try to do other attempts when have time.

**Comment by Digitalone1** [comment]
I did as you said and it's working as expected!

The only issue remaining is the application not exiting well, I have to kill it from task manager.

However, after dragging the plugin in the new position, I get the following warning:

```
(easyeffects:2763): Gtk-WARNING **: 10:15:45.837: Allocating size to GtkDragIcon 0x5640cc5e4160 without calling gtk_widget_measure(). How does the code know the size to allocate?

```

**Comment by Digitalone1** [comment]
As I'm seeing from the logs, the PipeManager destructor is not executed. That's tricky to resolve for me.

**Comment by Digitalone1** [comment]
@wwmm can you check why the PipeManager is not destructed? Thanks.

**Comment by Digitalone1** [comment]
Found the reason. Spectrum and Output Level classes are not destroyed. But why?

**Comment by wwmm** [comment]
Today is going to be a busy day so I do not know if I will be able to do a proper investigation. But after pulling your latest branch to my computer I see a potential problem
```
    auto list_size = list.size();
    auto links = pm->link_nodes(pm->pe_sink_node.id, plugins[list[0]]->get_node_id());

    for (const auto& link : links) {
      list_proxies.emplace_back(link);
    }

    for (size_t n = 0; n < list_size; n++) {
      if (!plugins[list[n]]->connected_to_pw) {
        plugins[list[n]]->connect_to_pw();
      }

      if (n > 0) {
        auto links = pm->link_nodes(plugins[list[n - 1]]->get_node_id(), plugins[list[n]]->get_node_id());

        for (const auto& link : links) {
          list_proxies.emplace_back(link);
        }
      }
    }
```
As this code is now it attempts to link `plugins[list[0]]` before checking if it is connected to PipeWire. Something like
```
      if (!plugins[list[0]]->connected_to_pw) {
        plugins[list[0]]->connect_to_pw();
      }
```
has to be done before
```
auto links = pm->link_nodes(pm->pe_sink_node.id, plugins[list[0]]->get_node_id());
```

**Comment by Digitalone1** [comment]
Counter is starting from 0, so the first plugin on 0 index is checked.

**Comment by wwmm** [comment]
>Counter is starting from 0, so the first plugin on 0 index is checked.

It is not going to help because a link to the first filter is done outside the for loop

**Comment by Digitalone1** [comment]
> > Counter is starting from 0, so the first plugin on 0 index is checked.
> 
> It is not going to help because a link to the first filter is done outside the for loop

Right. I will give a check.

**Comment by wwmm** [comment]
In any case the problem related to the app closing is being caused by something else.

**Comment by wwmm** [comment]
Looking atthe spectrum destructor I found a problem
```
  pw_thread_loop_lock(pm->thread_loop);

  if (connected_to_pw) {
    disconnect_from_pw();
  }

  pw_core_sync(pm->core, PW_ID_CORE, 0);

  pw_thread_loop_wait(pm->thread_loop);

  pw_thread_loop_unlock(pm->thread_loop);
```
you are locking the PiprWire main loop `pw_thread_loop_lock(pm->thread_loop);` before calling `disconnect_from_pw`. But the first thing that disconnect_from_pw does is trying to lock the main loop. But it can't do that because the first lock was not released.

**Comment by wwmm** [comment]
I think you can do the same thing you did to the other filters. Keep
```
if (connected_to_pw) {
    disconnect_from_pw();
  }
```
and remove the calls to the pipewire functions that are already inside `disconnect_from_pw`.

**Comment by Digitalone1** [comment]
Yes, that's the reason. Spectrum is the only class I did that, my mistake with copy-paste.

**Comment by Digitalone1** [comment]
Should be OK now. No issues to me. Please, test on your system @wwmm when you have time.

**Comment by wwmm** [comment]
I tested both pipelines and it seems fine :-)

**Pull request merged**
