### PR TITLE
App info UI management improved

### PR DESCRIPTION
**Pull request by Digitalone1**
Related to #1144

To be tested on wireplumber

### CODE REVIEW

**Comment by vchernin** [comment]
I tried building this and there is no change in behaviour with wireplumber
[easyeffects.log](https://github.com/wwmm/easyeffects/files/7193104/easyeffects.log)

**Comment by Digitalone1** [comment]
@vchernin Thanks for testing. The log does not give much help. I'm installing wireplumber on my system and try it out.

**Comment by lakotamm** [comment]
I compiled a flatpak with this commit (compiling from source on Fedora requires some harder to get packages). I did not notice any change either. :-/ 

(Fedora 35 Silverblue)

**Comment by Digitalone1** [comment]
> EDIT: after retesting, it seems like Easyeffects no longer crashes when the enable button is pressed, however it still does not process the sound. Also, the button does not stay enabled after a restart of the program.
> 
> (Fedora 35 Silverblue)

Do you confirm this is happening with pipewire-media-session disabled and wipeplumber enabled?

**Comment by lakotamm** [comment]
> Do you confirm this is happening with pipewire-media-session disabled and wipeplumber enabled?

Uff, I do not know how to confirm this.
I tried looking into the logs:

> [lakotamm@DESKTOP-4VU9AB6 ~]$ journalctl -xe | grep pipewire
> Sep 20 15:38:59 DESKTOP-4VU9AB6 rtkit-daemon[807]: Successfully made thread 1801 of process 1801 (/usr/bin/pipewire) owned by '1000' high priority at nice level -11.
> Sep 20 15:38:59 DESKTOP-4VU9AB6 rtkit-daemon[807]: Successfully made thread 1802 of process 1802 (/usr/bin/pipewire-pulse) owned by '1000' high priority at nice level -11.
> Sep 20 15:38:59 DESKTOP-4VU9AB6 rtkit-daemon[807]: Successfully made thread 1816 of process 1802 (/usr/bin/pipewire-pulse) owned by '1000' RT at priority 20.
> Sep 20 15:38:59 DESKTOP-4VU9AB6 rtkit-daemon[807]: Successfully made thread 1817 of process 1801 (/usr/bin/pipewire) owned by '1000' RT at priority 20.
> Sep 20 15:39:11 DESKTOP-4VU9AB6 wireplumber[1109]: disconnected from pipewire

According to this, wireplumber gets disconnected from pipewire after ca 25s since the start?

> [lakotamm@DESKTOP-4VU9AB6 ~]$  systemctl --user status pipewire.service
> ● pipewire.service - Multimedia Service
>      Loaded: loaded (/usr/lib/systemd/user/pipewire.service; disabled; vendor preset: disabled)
>     Drop-In: /usr/lib/systemd/user/pipewire.service.d
>              └─00-uresourced.conf
>      Active: active (running) since Mon 2021-09-20 15:38:59 CEST; 3min 23s ago
> TriggeredBy: ● pipewire.socket
>    Main PID: 1801 (pipewire)
>       Tasks: 2 (limit: 28340)
>      Memory: 12.1M
>         CPU: 282ms
>      CGroup: /user.slice/user-1000.slice/user@1000.service/session.slice/pipewire.service
>              └─1801 /usr/bin/pipewire
> 
> Sep 20 15:38:59 DESKTOP-4VU9AB6 systemd[1530]: Started Multimedia Service.

Since I have Silverblue, I could not have run the command for swapping wireplumber and pipewire-media-session (there is no `dnf swap`) in Silverblue.

**Comment by lakotamm** [comment]
Screenshot from 2021-09-20 15-49-50
I guess that this means that I have wireplumber active.

**Comment by wwmm** [comment]
I had time to test this PR now. So far I see no issues at all enabling or disabling Firefox while watching something on Twitch. The segmentation fault that was present when using WirePlumber is gone. As expected after the removal of the call that was doing this before.

**Comment by Digitalone1** [comment]
@lakotamm Check also with `systemctl --user is-enabled` if only wireplumber is enabled rather than pipewire-media-session.

Post here also the version of pipewire installed on the system.

**Comment by wwmm** [comment]
Another way is opening something like gnome system monitor. You should see only one of the session managers among the active processes.

**Comment by wwmm** [comment]
But like I said in another issue your problem seems to have other causes.

**Comment by Digitalone1** [comment]
@wwmm I did not have time yet to test this with wireplumber, but if it's working for you, it can be merged.

**Comment by lakotamm** [comment]
> @lakotamm Check also with `systemctl --user is-enabled` if only wireplumber is enabled rather than pipewire-media-session.
> 
> Post here also the version of pipewire installed on the system.

> [lakotamm@DESKTOP-4VU9AB6 ~]$ systemctl --user is-enabled wireplumber
> enabled
> [lakotamm@DESKTOP-4VU9AB6 ~]$ systemctl --user is-enabled pipewire-media-session
> Failed to get unit file state for pipewire-media-session.service: No such file or directory
> [lakotamm@DESKTOP-4VU9AB6 ~]$ systemctl --user is-enabled pipewire
> disabled

> $ pipewire --version
> pipewire
> Compiled with libpipewire 0.3.34
> Linked with libpipewire 0.3.34

**Comment by Digitalone1** [comment]
Arch has pipewire `0.3.36`. Maybe there's a compatibility issue on the old version.

**Pull request merged**
