### PR TITLE
Track nodes by pw serial

### PR DESCRIPTION
**Pull request by Digitalone1**
It seems to works. It has to be tested for days because this transition is error prone, but at least to me it's working just switching blocklist and presets.

Changed presets many times and only one time the app remained disabled. The rest it was working good (it could be more a pw issue).

I can't test with multiple outputs and inputs devices, so please do it @wwmm. Anyway I switched from speakers to headphone and no issues.

The only issue I had: `assertion 'default_value >= minimum && default_value <= maximum' failed` using `G_MININT64` as minimum parameter in `g_param_spec_uint64`, but I resolved replacing `SPA_ID_INVALID`. Maybe a casting issues, I commented the code reporting the workaround where this happened.

### CODE REVIEW

**Comment by wwmm** [comment]
So far everything is fine. Tomorrow I will take a look at some of the places where we still use the `id` when we actually wnat the device unique number. Like the code handling the autoloading profiles or any other accessing `pm->output_device.id` or `pm->input_device.id`.

**Comment by wwmm** [comment]
@Digitalone1 I have opened an issue in the Piepwire's page that may be of interest to you https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2409. As thing are right now trying to use object.serial in more cases is a pain. The amount of code we can actually move to object.serial now without a lot of pain is way smaller than what I had imagined. But at the same time we already have bugs related to the usage of `object.id`.

**Comment by Digitalone1** [comment]
I read the issue. The serial is good for streams since we introduced the timestamps to handle those bad apps like audacity that were spawning and closing lots of streams in very short time reusing id. Now with serial we have a new value at every new stream which is good.

But this is not what we want for devices. Did you test if there's a way to have a string uniquely associated to devices and use it to create links?

**Comment by wwmm** [comment]
>Did you test if there's a way to have a string uniquely associated to devices and use it to create links?

Not yet. I think I will have time for this only on Tuesday. The device object we currently use only because of the autoloading profiles has the base name without the things that are usually appended in the node's `object.name`. If the node had a property like this one with the base name it would be definitely viable to use it. But with the property in another object that has its own events I am not sure it is going to be useful.

**Pull request merged**
