### PR TITLE
Add Equal Mode to Filter, fix RRNoise UI and Ladspa Wrapper refactoring

### LINKED ISSUE #2570: Missing a parameter + a default value in the new filter plugin.
Hi guys, I was testing this effect in depth and noticed a few things were missing:

1. Equalizer Mode is absent. You should be able to choose between IIR, FIR, FFT or SPM processing.

2. The default value of Frequency is 10,000 Hz and not 2,000 Hz

Everything else is fine. Thank you very much for this wonderful effect :D

### PR DESCRIPTION
**Pull request by Digitalone1**
- Made a little refactoring to Ladspa Wrapper using literals, trying to avoid implicit conversions and making use of const where possible.
- - The use of `(unsigned long)-1` is funny. I suppose there's no alternative. ^^
- - No errors while testing this new ladpsa plugin, but I got warnings telling me that my system is too slow and after a while a core dump occurs. The issue is my old laptop.
- Added Equalizer Mode to LSP Filter (fixes #2570).
- Improved RNNoise UI.

### CODE REVIEW

**Comment by wwmm** [comment]
>but I got warnings telling me that my system is too slow

For some reason when the compiler is built in debug mode the ladspa initialization in the wrapper is very slow. But the normal binary runs fine on my computer.

**Comment by wwmm** [comment]
Looking at the code it seemed fine but something is weird when running the deepfilternet plugin. I will have to investigate more why

**Comment by wwmm** [comment]
Yeah... The plugin is not working the same way with the changes in the PR. IT wil probably be better to merge the other changes in a seperate PR and investigate later what is going wrong with the changes to the deepfilter.

**Comment by wwmm** [comment]
And it did not take long for the non debug binary to crash. What I never saw it doing before.

**Comment by wwmm** [comment]
>The plugin is not working the same way with the changes in the PR.

By this I meant it was not filtering the signal right. It was removing the voice where the version without the patch removed only the noise.

**Comment by Digitalone1** [comment]
@wwmm Just drop all the commits related to the Ladspa wrapper, leaving the ones for the Filter and the RNNoise should be fine.

**Comment by Digitalone1** [comment]
I will try to make small commits and test on my other laptop which should be faster to let me test without crashing.

**Comment by wwmm** [comment]
>Just drop all the commits related to the Ladspa wrapper, leaving the ones for the Filter and the RNNoise should be fine.

Revert the revert and then delete the ones for the wrapper? I will try it.

**Comment by Digitalone1** [comment]
@wwmm For me tt's hard to test which is the issue. I keep getting core dumps even at the current state:

```
2023-10-17T13:21:15.650Z | WARN |  deep_filter_ladspa | DF 63c75f263811 | Underrun detected (RTF: 7.36). Processing too slow!
2023-10-17T13:21:15.672Z | WARN |  deep_filter_ladspa | DF 63c75f263811 | Underrun detected (RTF: 1.05). Processing too slow!
2023-10-17T13:21:15.696Z | WARN |  deep_filter_ladspa | DF 63c75f263811 | Underrun detected (RTF: 1.06). Processing too slow!
(easyeffects:27874): easyeffects-DEBUG: 15:21:15.696: 	output_level.cpp:37	soe: output_level: PipeWire blocksize: 1024
(easyeffects:27874): easyeffects-DEBUG: 15:21:15.696: 	output_level.cpp:38	soe: output_level: PipeWire sampling rate: 48000
2023-10-17T13:21:15.761Z | WARN |  deep_filter_ladspa | DF 63c75f263811 | Underrun detected (RTF: 2.03). Processing too slow!
2023-10-17T13:21:15.827Z | WARN |  deep_filter_ladspa | DF 63c75f263811 | Underrun detected (RTF: 2.11). Processing too slow!
2023-10-17T13:21:15.870Z | WARN |  deep_filter_ladspa | DF 63c75f263811 | Underrun detected (RTF: 2.01). Processing too slow!
2023-10-17T13:21:15.939Z | WARN |  deep_filter_ladspa | DF 63c75f263811 | Underrun detected (RTF: 2.21). Processing too slow!
2023-10-17T13:21:16.006Z | WARN |  deep_filter_ladspa | DF 63c75f263811 | Underrun detected (RTF: 2.12). Processing too slow!
2023-10-17T13:21:16.029Z | WARN |  deep_filter_ladspa | DF 63c75f263811 | Underrun detected (RTF: 1.05). Processing too slow!
2023-10-17T13:21:16.052Z | WARN |  deep_filter_ladspa | DF 63c75f263811 | Underrun detected (RTF: 1.06). Processing too slow!
2023-10-17T13:21:16.077Z | WARN |  deep_filter_ladspa | DF 63c75f263811 | Underrun detected (RTF: 1.15). Processing too slow!
2023-10-17T13:21:16.123Z | WARN |  deep_filter_ladspa | DF 63c75f263811 | Underrun detected (RTF: 2.11). Processing too slow!
```

**Comment by Digitalone1** [comment]
> For some reason when the code is built in debug mode the ladspa initialization in the wrapper is very slow. But the normal binary runs fine on my computer.

Not for me. Tried installing from the AUR and it's the same. My laptop is old, but I'm afraid lots of users will be affected.

I will try to install on my newer laptop, but I don't have all the developing stuff there...

**Comment by wwmm** [comment]
>For me it's hard to test which is the issue. I keep getting core dumps even at the current master state:

Ok. I will try to figure out exactly what in the patches caused the filter to misbehave.

**Comment by wwmm** [comment]
First test
```
git cherry-pick decd964
```
This is fine. So the consts added in this commit are fine.

**Pull request merged**
