### PR TITLE
Flatpak CI builds

### PR DESCRIPTION
**Pull request by vchernin**
This seems to be working. To see artfiacts you need to go to the workflow details, them the summary page. Go there by clicking the "details" of "CI/ flatpak" above the merge button. Note this doesn't show up in this PR, only after merge on new PRs in this repo.

This also introduces a bot here to make PRs when the Flatpak dependencies get an update. 

Unauthenticated users (i.e. no github account) can't download the artifact, however that can be workarounded with [nightly.link](https://nightly.link), which I have left until later to look at.

Maybe there could be bot to comment a link to the build ([like on flathub](https://github.com/flathub/com.github.wwmm.easyeffects/pull/162)), but that could also be a bit spammy. I also think it would be nice to have build artifacts for arch since we already have a pkgbuild here.

### CODE REVIEW

**Comment by wwmm** [comment]
>I also think it would be nice to have build artifacts for arch since we already have a pkgbuild here.

For Arch there is already a circleci build https://app.circleci.com/pipelines/github/wwmm/easyeffects?branch=master. Would there be an advantage in implement the same through artifacts?

**Comment by vchernin** [comment]
> For Arch there is already a circleci build https://app.circleci.com/pipelines/github/wwmm/easyeffects?branch=master. Would there be an advantage in implement the same through artifacts?

To be clear an "artifact" is just some output from the build, e.g. a installable flatpak bundle or a installable arch binary package. Circle CI doesn't seem to be producing any Arch artifacts currently, so if users want to test a PR or master they will still have to build it themselves like with easyeffects-git from AUR. 

It is likely possible to get Circle CI to produce Arch artifacts, but I'm not very familar with it.

I'm also wondering if you have an opinion on a comment bot, [similar to on flathub](https://github.com/flathub/com.github.wwmm.easyeffects/pull/162)? It would make it more straighforward for users to see a build is testable. Although it could be done with just one comment that auto updates.

**Comment by vchernin** [comment]
Actually I see now there is some info here, https://app.circleci.com/pipelines/github/wwmm/easyeffects/2843/workflows/3783ca42-3141-4858-9e3a-7d6fc48e76a0/jobs/2843/artifacts. I could just try and implement that, but the problem is I'm not sure if there is an easy way to make the artifact discoverable from github.

**Comment by wwmm** [comment]
>I'm also wondering if you have an opinion on a comment bot, https://github.com/flathub/com.github.wwmm.easyeffects/pull/162?

I think they can be good on pull requests. There is a circleci status icon there but I bet most people do not click on it to see if the build succeeded.

**Pull request merged**
