### PR TITLE
about: Port to AdwAboutWindow

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
**Disclaimer: I know very little about C++!**

I only grabbed users with the most amount of contributions, but I didn't add everyone.

People to credit:
- @vchernin
- @Digitalone1

### CODE REVIEW

**Comment by wwmm** [comment]
I think it may be a little weird to do that without asking these people first. Maybe they do not want their names in the about window. And in some cases like the one from `hosiet`, `Mikhail` and `Vincent`  it is more about maintaining distribution packages. This is something that is mostly done independently of the work in EasyEffects repository. Flatpak is the only exception. Maybe author isn't the best tag for them. At least `artists`, `translators` and `documentators` have their own field in the about window. Hopefully there is one for package maintainers.

I think it is better to wait for each person manifestation and add the credits ondemand. Specially because some of these contributors haven't actively participated for some years.

**Comment by TheEvilSkeleton** [comment]
> In any case I think it is better to wait for each person manifestation and add the credits ondemand. Specially because some of these contributors haven't actively participated for some years.

Good point. I removed everyone. That being said, we can add a credit section via [`add_credit_section`](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/method.AboutWindow.add_credit_section.html).

**Comment by wwmm** [comment]
I wonder if it is worth having an open issue where contributors interested in having their names in the about section could manifest their opinions. A PR page may not have the proper dynamic for this. What do you think @Digitalone1 and @vchernin? You two have contributed a lot to the project. So it is obviously fine to have your names in the about page if you want it.

**Comment by vchernin** [comment]
I think a new issue for this is a good idea, and yeah I would be fine with my name in the about page.

**Comment by Digitalone1** [comment]
Hello, no problem in having `Giusy Digital` in the About section. I don't like to share my real name, but that's a pseudonym on Github, so it's okay to use it for me. :)

**Comment by TheEvilSkeleton** [comment]
@wwmm Should I add @Digitalone1 and @vchernin's names right now or is it better if they add themselves in separate MRs later?

**Comment by Digitalone1** [comment]
Waiting for @vchernin answer, you can add `Giusy Digital`.

**Comment by TheEvilSkeleton** [comment]
@vchernin said that they're okay with adding their name, but I want to know if @wwmm wants the respective contributors to add themselves in the list or if we can add your names in this MR.

I'm asking because I don't want to spam CI artifacts and waste resources for no reason.

**Comment by wwmm** [comment]
I can add them after merging the pull request.

**Pull request merged**
