### PR TITLE
spectrum: use gtk tick callback to trigger spectrum redraws

### PR DESCRIPTION
**Pull request by tleb**
Related issue: #3224. Related previous PR: #3231.

I have written all informations inside commit messages. The last one is the bulk of the series.

 - We start by some cleanup: we switch all `std::vector` in Spectrum to being arrays. This avoids `.resize()` calls inside the constructor. The goal is simpler code, it is not an optimization.
 - We then switch `PluginBase::bypass` to become atomic. This allows removing the `data_mutex` locking in `Spectrum`.
 - We switch `fftw_ready` to become atomic as well.
 - We use `std::memmove()` to shift previous samples. This improves the average time spent inside `process()`.
 - We finish by switching the main patch. It changes the way spectrum chart redraw is being scheduled.

After this patch series, `Spectrum::process()` does not appear anymore in a `perf` recording, and we get a 60FPS (or more depending on display) spectrum chart.

---

Some stats on my workstation. 256 quantum, 48kHz sample rate, ran 45 seconds, no other load.

```
           before      after
calls        8912       8923
avg (µs)       65.0       34.2
stdev          16.9        7.6
min             0.0        7.0
5th perc       39.0       20.0
25th perc      54.0       29.0
median         69.0       35.0
75th perc      74.0       40.0
95th perc      82.0       43.0
max           151.0      127.0
```

---

I use this small patch to dump chart redraw interval timings:

<details>
```diff
diff --git a/src/chart.cpp b/src/chart.cpp
index 8e9d53b13..91f609905 100644
--- a/src/chart.cpp
+++ b/src/chart.cpp
@@ -249,6 +249,8 @@ void set_x_data(Chart* self, const std::vector<double>& x) {
   });
 }

+static gint64 time_since_last_drawing;
+
 void set_y_data(Chart* self, const std::vector<double>& y) {
   if (!GTK_IS_WIDGET(self) || y.empty()) {
     return;
@@ -280,6 +282,10 @@ void set_y_data(Chart* self, const std::vector<double>& y) {
   }

   gtk_widget_queue_draw(GTK_WIDGET(self));
+
+  gint64 time = g_get_monotonic_time();
+  printf("%.0f ms\n", (double)(time - time_since_last_drawing) / (1e3));
+  time_since_last_drawing = time;
 }

 void on_pointer_motion(GtkEventControllerMotion* controller, double xpos, double ypos, Chart* self) {
```
</details>

### CODE REVIEW

**Comment by wwmm** [comment]
Thanks! For some reason I never thought about using std::atomic. So far no problems on my computer.

**Comment by wwmm** [comment]
I feel like I will forget in a few days what is being done by those bitwise operations but it is not a big concern :smile: . I rarely touch bitwise operations. It may be a good thing to add some comments explaining how the code around `compare_exchange_weak` works.

**Comment by tleb** [comment]
I thought about extracting that *mess* into a separate abstraction and comment it (excessively), but my C++ skills (or lack of) meant I wasn't confident enough to create an abstraction and reason about what happens to data (copying, references, templating, move semantic, operators to implement, all that crap).

I'm saying that because I wouldn't be surprised that the double-buffering thing could be used elsewhere. Whenever you want to extract a lot of data from realtime into GUI thread. "A lot of data" is everything bigger than what can be done atomically, ie often `2*sizeof(void*)`.

**Comment by wwmm** [comment]
>I thought about extracting that mess into a separate abstraction and comment it (excessively), but my C++ skills (or lack of) meant I wasn't confident enough to create an abstraction and reason about what happens to data (copying, references, templating, move semantic, operators to implement, all that crap).

It is fine even if it is a superficial explanation :-).

>About atomics: it might mean we could remove a bunch of mutexes from plugins. I haven't looked much yet. I might go for a hunt!

I think we do not have many. But the few we have probably can be replaced by an atomic.

I have started to work on a Qt port in a secondary branch. It will be a long journey. But I can already say that any work on optimizations heavily dependent on gtk or gsettings calls should be avoided. The files unrelated to the ui or the database probably will be reused without major changes. So it is fine to invest energy in the classes managing the filters.

**Pull request merged**
