### PR TITLE
Fix node linking and string conversion

### LINKED ISSUE #1098: #1091 causes build failure
4aae411d2f432caae887fd2b6a595f18e8c71022 from #1091 reliably causes the local Flatpak build to fail when building EasyEffects. Using the previous commit f5ef2adea626dcde28f306c626067e5d7cf2b5cf is fine.
```
[81/105] Compiling C++ object src/easyeffects.p/plugin_ui_base.cpp.o
FAILED: src/easyeffects.p/plugin_ui_base.cpp.o 
ccache c++ -Isrc/easyeffects.p -Isrc -I../src -I../include -I. -I.. -Idata -I/app/include/pipewire-0.3 -I/app/include/spa-0.2 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/app/include/glibmm-2.68 -I/app/lib/glibmm-2.68/include -I/app/include/sigc++-3.0 -I/app/lib/sigc++-3.0/include -I/usr/include/gtk-4.0 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/graphene-1.0 -I/usr/lib/x86_64-linux-gnu/graphene-1.0/include -I/usr/include/gio-unix-2.0 -I/app/include/gtkmm-4.0 -I/app/lib/gtkmm-4.0/include -I/app/include/giomm-2.68 -I/app/lib/giomm-2.68/include -I/app/include/cairomm-1.16 -I/app/lib/cairomm-1.16/include -I/app/include/pangomm-2.48 -I/app/lib/pangomm-2.48/include -I/usr/include/gtk-4.0/unix-print -I/app/include/lilv-0 -I/app/include/serd-0 -I/app/include/sord-0 -I/app/include/sratom-0 -I/app/include/bs2b -I/app/include/ -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++20 -O2 -g '-DG_LOG_DOMAIN="easyeffects"' -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -pthread -mfpmath=sse -msse -msse2 -mfpmath=sse -msse -msse2 -D_REENTRANT -MD -MQ src/easyeffects.p/plugin_ui_base.cpp.o -MF src/easyeffects.p/plugin_ui_base.cpp.o.d -o src/easyeffects.p/plugin_ui_base.cpp.o -c ../src/plugin_ui_base.cpp
../src/plugin_ui_base.cpp: In static member function ‘static float PluginUiBase::string_to_float(const string&)’:
../src/plugin_ui_base.cpp:69:80: error: no matching function for call to ‘from_chars(const char*, const char*, float&)’
   69 |   auto [ptr, ec] = std::from_chars(value.data(), value.data() + value.size(), n);
      |                                                                                ^
In file included from ../src/plugin_ui_base.cpp:21:
/usr/include/c++/10.2.0/charconv:595:5: note: candidate: ‘template<class _Tp> std::__detail::__integer_from_chars_result_type<_Tp> std::from_chars(const char*, const char*, _Tp&, int)’
  595 |     from_chars(const char* __first, const char* __last, _Tp& __value,
      |     ^~~~~~~~~~
/usr/include/c++/10.2.0/charconv:595:5: note:   template argument deduction/substitution failed:
In file included from /usr/include/c++/10.2.0/bits/move.h:57,
                 from /usr/include/c++/10.2.0/bits/stl_pair.h:59,
                 from /usr/include/c++/10.2.0/bits/stl_algobase.h:64,
                 from /usr/include/c++/10.2.0/bits/char_traits.h:39,
                 from /usr/include/c++/10.2.0/string:40,
                 from /app/include/glibmm-2.68/glibmm/base64.h:23,
                 from /app/include/glibmm-2.68/glibmm.h:100,
                 from /app/include/giomm-2.68/giomm.h:22,
                 from ../include/plugin_ui_base.hpp:23,
                 from ../src/plugin_ui_base.cpp:20:
/usr/include/c++/10.2.0/type_traits: In substitution of ‘template<bool _Cond, class _Tp> using enable_if_t = typename std::enable_if::type [with bool _Cond = false; _Tp = std::from_chars_result]’:
/usr/include/c++/10.2.0/charconv:584:11:   required by substitution of ‘template<class _Tp> using __integer_from_chars_result_type = std::enable_if_t<std::__or_<std::__or_<std::is_same<typename std::remove_cv< <template-parameter-1-1> >::type, signed char>, std::is_same<typename std::remove_cv< <template-parameter-1-1> >::type, short int>, std::is_same<typename std::remove_cv< <template-parameter-1-1> >::type, int>, std::is_same<typename std::remove_cv< <template-parameter-1-1> >::type, long int>, std::is_same<typename std::remove_cv< <template-parameter-1-1> >::type, long long int> >, std::__or_<std::is_same<typename std::remove_cv< <template-parameter-1-1> >::type, unsigned char>, std::is_same<typename std::remove_cv< <template-parameter-1-1> >::type, short unsigned int>, std::is_same<typename std::remove_cv< <template-parameter-1-1> >::type, unsigned int>, std::is_same<typename std::remove_cv< <template-parameter-1-1> >::type, long unsigned int>, std::is_same<typename std::remove_cv< <template-parameter-1-1> >::type, long long unsigned int> >, std::is_same<char, typename std::remove_cv< <template-parameter-1-1> >::type> >::value, std::from_chars_result> [with _Tp = float]’
/usr/include/c++/10.2.0/charconv:595:5:   required by substitution of ‘template<class _Tp> std::__detail::__integer_from_chars_result_type<_Tp> std::from_chars(const char*, const char*, _Tp&, int) [with _Tp = float]’
../src/plugin_ui_base.cpp:69:80:   required from here
/usr/include/c++/10.2.0/type_traits:2554:11: error: no type named ‘type’ in ‘struct std::enable_if<false, std::from_chars_result>’
 2554 |     using enable_if_t = typename enable_if<_Cond, _Tp>::type;
      |           ^~~~~~~~~~~
[88/105] Compiling C++ object src/easyeffects.p/presets_manager.cpp.o
ninja: build stopped: subcommand failed.
Error: module easyeffects: Child process exited with code 1
```

@Digitalone1 any ideas?

I tried to build the Arch package against this commit, but I'm not familar enough with the PKGBUILD syntax to do so.

### PR DESCRIPTION
**Pull request by Digitalone1**
Related to #1095 

Edit: Fixes #1098

### CODE REVIEW

**Comment by Digitalone1** [comment]
@wwmm I don't have a microphone. Please test on your system. Speakers are working to me.

**Comment by wwmm** [comment]
I think this code is not going to fix the mic problem .The reason is that the input device that can have only one channel is `pm->input_device.id`. The device `pm->pe_source_node.id` is our virtual source and that one will have 2 channels always.

**Comment by wwmm** [comment]
I also think that on old code will link to mono output devices. As that device is the last to be handled the `link_size < 2` check after the last call to `auto links = pm->link_nodes(prev_node_id, next_node_id);` does nothing. The issue I opened at the PipeWire page will be there for other reasons. But the check should not be causing problems for one channel output devices. The mic pipeline is having problems because the first link is from the mic to the first filter. If that check does not see 2 channels it keeps trying to link to next filter and so on. That is why his mic had one link to every filter.

If you want I can handle that problem with the mic. But first I want to take a look at the crystalizer plugin.  Something is wrong with its band splitting.

**Comment by Digitalone1** [comment]
I understood now, will make a force push with a new fix.

**Comment by Digitalone1** [comment]
As I understood, mono output devices get connected because the two output ports of `output_level` node are connected to the same input port of output device, establishing two links. Since this device can also have more than 2 channels, maybe also other ports get linked, so more than two links are established (even if a remap sink is needed in the future as stated in pw issue). Therefore, checking errors on `link_size < 2` should cover all possibilities.

For input stream, the check is different whether the mic is successfully connected to a node or not. If it's alreaady connected to a node, we have to be sure the links are exactly two, otherwise at least one link has to be established.

Should be fine now. Please, test with a mic on your system.

**Pull request merged**
