### PR TITLE
Sort imported equalizer band filters

### PR DESCRIPTION
**Pull request by bhack**
https://github.com/wwmm/easyeffects/issues/1733#issuecomment-1267240702

### CODE REVIEW

**Comment by Digitalone1** [comment]
Thanks @bhack 

For our code style there's no need of the `else` statement after a `return`.

Please, write it as:

```c++
  if (filter_type.empty()) {
    return false;
  } 

  std::ranges::stable_sort(bands, {}, &APO_Band::freq);
```

**Comment by Digitalone1** [comment]
And, please, can you do the same also for GraphicEq import? Thanks.

Here: https://github.com/wwmm/easyeffects/blob/master/src/equalizer_ui.cpp#L507

**Comment by bhack** [comment]
Done

**Comment by bhack** [comment]
Sorting it could go to impact the UI in the case of reduction to a subset N filters:

https://github.com/jaakkopasanen/AutoEq/tree/master/results/oratory1990/harman_over-ear_2018/1MORE%20Triple%20Driver%20Over%20Ear#parametric-eqs

**Pull request merged**
