### PR TITLE
Icons fixed and changelog updated

### LINKED ISSUE #1047: Output app list doesn't display icons of Flatpak applications
In the output section, while audio can be manipulated for Flatpak apps, the icon for the app doesn't seem to show. This issue is specifically about other apps being a Flatpak, which affects both the Arch package and the EasyEffects Flatpak. 

Arch package with Chromium Flatpak installed:
image

Flatpak Package with Chromium Flatpak:
image

Tested on Arch with KDE, also occurs on GNOME.

### LINKED ISSUE #1050: Plugins "puzzle piece" icon not visible on KDE
I had some issues with icons and text not displaying while testing the Flatpak on KDE.
The majority of these were solved for the Flatpak by installing `xdg-desktop-portal-gtk` on the host system.

However one issue seems to remain for both the Arch package and the Flatpak:

Arch package:
image

Flatpak:
image

The plugin "puzzle piece" icon isn't visible in the bottom center. This doesn't occur for me on GNOME:
image

Sidenote about theming in general:
Do you prefer the app to follow the Adwaita theme everywhere by default? Currently there doesn't seem to be much support for GTK 4 themes integrated in Flatpak yet, so by default on KDE the Flatpak will look as shown.

However, by workarounding with `sudo flatpak override --filesystem=~/.themes` all Flatpaks are given access to the system themes, so the [Flatpak looks identical to the Arch package](https://user-images.githubusercontent.com/38842733/127287795-141e53d7-85b5-4a51-975b-97d796a89cd4.png). This particular puzzle piece icon issue occurs either way though.

Edit: somehow I took all these screenshots without realizing there's a black bar where actual info should be. I guess that's a bug too. I'll try to figure that out later. Edit: that's just because I haven't started playing audio yet.

### PR DESCRIPTION
**Pull request by Digitalone1**
Fixes #1047 
Fixes #1050 

There are also some optimizations and text changes coming from clang-format.

### CODE REVIEW

**Comment by wwmm** [comment]
It is not related to this pull request but at some point we introduced a regression in the code that switches output devices when the user changes the default. I will take a look. I am doing tests now with my second sound card and EasyEffects is not switching automatically to the new default device after a new selection is done in pavucontrol. Strange...

**Comment by Digitalone1** [comment]
I can try to test with the hdmi port on my laptop. Tell me where the switch is done in the code and I'll take a look tomorrow.

**Comment by wwmm** [comment]
I've found the source of the regression. And it is really subtle. In the callback of the signal `settings->signal_changed("output-device").connect` the following line
```
const auto& name = settings->get_string(key).raw();
```
has to be replaced by
```
const auto name = settings->get_string(key).raw();
```
I think that `auto&` may have created a pointer to a pointer instead of passing by reference. The output of the `raw()` method is already a `const std::string&`.

**Comment by wwmm** [comment]
Master branch updated with the fix.

**Comment by Digitalone1** [comment]
So if I explicitly need a reference to a std::string, I have to construct a new string from raw().

Later I'll give a check to other `raw()` inside the code.

**Pull request merged**
