### PR TITLE
Improve internal blocklist handling + App tags

### PR DESCRIPTION
**Pull request by Digitalone1**
Related to #1128, #1335, #1541 and #1546.

I think this is better because we check for Pavucontrol only in `on_node_info` looking at app id rather than trying to do it in `on_registry_global` and then checking for stream monitor key later.

It's better to look for node names since it's done only the first time when the node is added, but this is not reliable for localized app names (Pavucontrol), so I think those changes are a cleaner approach.

Regarding OBS and capture streams, I excluded the latter in `on_node_info` and there we could add a gsettings key to let the user allow/deny this task. We can discuss if it's convenient blocking `OBS` directly checking the name or just excluding all the capture streams.

Since we talked about app id, I wonder why we don't set it for our nodes. Maybe should we do it?

I mark this as draft, fell free to change/improve it.

### CODE REVIEW

**Comment by wwmm** [comment]
>Since we talked about app id, I wonder why we don't set it for our nodes. Maybe should we do it?

Unfortunately almost no player sets `application.id` in streams. There isn't much point in adding this property to our nodes as things are right now. And in EasyEffects only the blocklist uses this id if the audio application sets it.

We could create this property in the node info. But it is not going to make much difference.

**Comment by Digitalone1** [comment]
I know, but since we ask to set id for a better blocklist handling, we should set if before as an example to follow.

**Comment by Digitalone1** [comment]
Another thing I'd like to do is getting rid of timestamps and rely only on serials to track nodes, which should be unique unlike node id, as the pipewire doc says.

**Comment by wwmm** [comment]
>Another thing I'd like to do is getting rid of timestamps and rely only on serials to track nodes, which should be unique unlike node id, as the pipewire doc says.

Yes. I think we should also drop any reference to the `object.id`. It may still have some use for PipeWire internally but in our case we want something that is unique for the object. I think I will have time to do something about this tomorrow. But let me know in case you have already started to replace things by `object.serial`.

About `ee_app_id` I think it may be better to define this in a new header file independently from `pipe_manager.hpp`. This id string isn't conceptually tied to the PipeWire class. I also think calls to runtime objects like 
```
self->data->application->pm->ee_app_id.c_str()
```
can probably be avoided because the variable is static anyway. An approach similar to https://github.com/wwmm/easyeffects/blob/master/include/equalizer_tags.hpp may work.

**Comment by wwmm** [comment]
Or maybe just something like `auto constexpr log_tag = "com.github.wwmm.easyeffects";` inside a header only for ids. If the destination location needs it to be a string `using namespace std::string_literals;` could be used as needed.

**Comment by Digitalone1** [comment]
I'm not working on the serial, but I made a new header for app tags. Will make a new commit in the next hours.

**Comment by Digitalone1** [comment]
I think it's way better now. Unfortunately I couldn't make strings as `constexpr` because of a compiler error, but I think it's good as it is.

If you want, I could add a specific config to enable/disable the capture streams.

The config could be named `Exclude capture streams` and it would be `true` as default.

**Comment by wwmm** [comment]
>The config could be named Exclude capture streams and it would be true as default.

Ok. I think I can do this today.

**Comment by wwmm** [comment]
It seems `object.serial` can not be used to reset or set `PW_KEY_NODE_TARGET`. For this one we have to use `object.id`... Weird...

**Comment by wwmm** [comment]
>Exclude capture streams

On a second though I think this may give the wrong idea that all recorder streams will be excluded. Only capture streams that monitor devices will be exclude. Maybe `Exclude Device Monitor Streams` is a better description.

**Comment by Digitalone1** [comment]
> > Exclude capture streams
> 
> On a second though I think this may give the wrong idea that all recorder streams will be excluded. Only capture streams that monitor devices will be exclude. Maybe `Exclude Device Monitor Streams` is a better description.

You're right.

**Comment by Digitalone1** [comment]
I'm working on it. Hope to do a MR in the next hours.

**Pull request merged**
