### PR TITLE
Fix Maximum History in Autogain

### PR DESCRIPTION
**Pull request by Digitalone1**
I'm trying to fix the issue shown in #1524 regarding the Maxmium History in Autogain.

Meanwhile I uniformed the calls to prepare widgets.

### CODE REVIEW

**Comment by Digitalone1** [comment]
So, `g_settings_get_int` is called inside `set_maximum_history` even if it's already called before. I modified the code to use the values passed by reference.

But I can't resolve the issue. Using debug strings I saw the execution stops inside `ebur128_set_max_history`, so it should be an issue related to libebur128.

I tried also to pass the gsettings value "by value" rather than reference, but nothing changes. I ended up only making a static cast since the value expected is unsigned long as reported [here](https://github.com/jiixyj/libebur128/blob/67b33abe1558160ed76ada1322329b0e9e058b02/ebur128/ebur128.h#L206).

Any idea @wwmm?

**Comment by Digitalone1** [comment]
I answer here.

> I have no problems at all with the maximum history control in the autogain window. Even If I change it while audio is being processed. But whatever it is happening in your computers I agree it has nothing to do with the preset bug.

That's really weird. I can always reproduce the issue. I can't change the maximum history value and it's the only parameter giving this problem and getting a segmentation fault.

**Comment by wwmm** [comment]
>That's really weird. I can always reproduce the issue. I can't change the maximum history value and it's the only parameter giving this problem and getting a segmentation fault.

Try to run the executable inside gdb or running `sudo coredumpctl gdb` as soon as EasyEffects crashes. If you can reproduce but I can't my guess is a multithreading problem somewhere.

**Comment by Digitalone1** [comment]
> > That's really weird. I can always reproduce the issue. I can't change the maximum history value and it's the only parameter giving this problem and getting a segmentation fault.
> 
> Try to run the executable inside gdb or running `sudo coredumpctl gdb` as soon as EasyEffects crashes. If you can reproduce but I can't my guess is a multithreading problem somewhere.

```
Thread 1 "easyeffects" received signal SIGSEGV, Segmentation fault.
0x00007ffff6dffbb1 in ebur128_set_max_history () from /usr/lib/libebur128.so.1
(gdb) bt
#0  0x00007ffff6dffbb1 in ebur128_set_max_history ()
    at /usr/lib/libebur128.so.1
#1  0x0000555555612a03 in AutoGain::set_maximum_history(int const&) ()
#2  0x000055555561249d in AutoGain::AutoGain(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, PipeManager*)::{lambda(_GSettings*, char*, void*)#2}::operator()(_GSettings*, char*, void*) const ()
#3  0x000055555561250d in AutoGain::AutoGain(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, PipeManager*)::{lambda(_GSettings*, char*, void*)#2}::_FUN(_GSettings*, char*, void*) ()
#4  0x00007ffff72317f5 in g_cclosure_marshal_VOID__STRINGv ()
    at /usr/lib/libgobject-2.0.so.0
#5  0x00007ffff72506b6 in g_signal_emit_valist ()
    at /usr/lib/libgobject-2.0.so.0
#6  0x00007ffff7250824 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#7  0x00007ffff7364637 in  () at /usr/lib/libgio-2.0.so.0
#8  0x00007ffff72f0145 in  () at /usr/lib/libgio-2.0.so.0
#9  0x00007ffff72506b6 in g_signal_emit_valist ()
    at /usr/lib/libgobject-2.0.so.0
#10 0x00007ffff7250824 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#11 0x00007ffff7365f4f in  () at /usr/lib/libgio-2.0.so.0
#12 0x00007ffff7360d5f in  () at /usr/lib/libgio-2.0.so.0
#13 0x00007ffff7dd7825 in g_main_context_invoke_full ()
    at /usr/lib/libglib-2.0.so.0
#14 0x00007ffff7361511 in  () at /usr/lib/libgio-2.0.so.0
#15 0x00007ffff24d9f8f in  () at /usr/lib/gio/modules/libdconfsettings.so
#16 0x00007ffff24da2b2 in  () at /usr/lib/gio/modules/libdconfsettings.so
#17 0x00007ffff73b7d8f in  () at /usr/lib/libgio-2.0.so.0
#18 0x00007ffff73718d3 in  () at /usr/lib/libgio-2.0.so.0
#19 0x00007ffff7232f8f in g_closure_invoke ()
    at /usr/lib/libgobject-2.0.so.0
#20 0x00007ffff724eba8 in  () at /usr/lib/libgobject-2.0.so.0

```

**Comment by wwmm** [comment]
Humm... I have an idea. Let try to change the history before allowing the plugin to be initialized. In other words before starting a stream

**Comment by Digitalone1** [comment]
Can you merge and work from here?

**Comment by wwmm** [comment]
>I have an idea. Let try to change the history before allowing the plugin to be initialized. In other words before starting a stream

That is it. Now I see the crash. The problem is that `set_maximum_history` is not checking if `ebur_state` is not a `nullptr`. The pointer `ebur_state` is only initialized after the processing function from the filter is called. What is only going to happen if a stream is being processed in EasyEffects. I probably never tried to change this parameter when nothing was playing.

**Comment by wwmm** [comment]
Fixed in the master branch.

**Pull request merged**
